version: '3.4'

networks:
  internal-net:
    driver: bridge
    internal: true
  external-net:
    driver: bridge

services:
  rabbitmq: # login guest:guest
    image: rabbitmq:3-management
    hostname: "rabbitmq"
    labels:
      NAME: "rabbitmq"
    ports:
      - "4369:4369"
      - "5671:5671"
      - "5672:5672"
      - "25672:25672"
      - "15671:15671"
      - "15672:15672"
    networks:
      - internal-net
    restart: always

  db:
    image: "mcr.microsoft.com/mssql/server"
    hostname: "db"
    labels:
      NAME: "db"
    environment:
      SA_PASSWORD: "${DBPASS}"
      ACCEPT_EULA: "${ACCEPT_EULA}"
    ports:
      - "${DBPORT}:1433"
    networks:
      - internal-net
    restart: always

  rapitest:
    image: jarbounds/rapitest:latest
    depends_on:
      db:
        condition: service_started
      rabbitmq:
        condition: service_started
    environment:
      DBHOST: "${DBHOST}"
      DBPORT: "${DBPORT}"
      DBUSER: "${DBUSER}"
      DBPASS: "${DBPASS}"
      REGISTER_SECRET: "${REGISTER_SECRET}"
    ports:
        - "443:443"
    networks:
      - internal-net
      - external-net
    restart: always

  runtestsworkerservice:
    image: jarbounds/runtestsworkerservice:latest
    depends_on:
      db:
        condition: service_started
      rabbitmq:
        condition: service_started
    environment:
      DBHOST: "${DBHOST}"
      DBPORT: "${DBPORT}"
      DBUSER: "${DBUSER}"
      DBPASS: "${DBPASS}"
      MQHOST: "${MQHOST}"
      MQPORT: "${MQPORT}"
    networks:
      - internal-net
      - external-net
    restart: always


  setuptestsworkerservice:
    image: jarbounds/setuptestsworkerservice:latest
    depends_on:
      db:
        condition: service_started
      rabbitmq:
        condition: service_started
    environment:
      DBHOST: "${DBHOST}"
      DBPORT: "${DBPORT}"
      DBUSER: "${DBUSER}"
      DBPASS: "${DBPASS}"
      MQHOST: "${MQHOST}"
      MQPORT: "${MQPORT}"
    networks:
      - internal-net
    restart: always