version: '3.4'

networks:
  internal-net:
    driver: bridge
    internal: true
  external-net:
    driver: bridge

services:
  rabbitmq: # login guest:guest
    image: rabbitmq:3-management
    hostname: "rabbitmq"
    labels:
      NAME: "rabbitmq"
    ports:
      - "4369:4369"
      - "5671:5671"
      - "5672:5672"
      - "25672:25672"
      - "15671:15671"
      - "15672:15672"
    networks:
      - internal-net
    restart: always

  db:
    image: "mcr.microsoft.com/azure-sql-edge:latest"
    hostname: "db"
    labels:
      NAME: "db"
    environment:
      SA_PASSWORD: "${SA_PASSWORD}"
      ACCEPT_EULA: "${ACCEPT_EULA}"
    ports:
      - "1433:1433"
    networks:
      - internal-net
      - external-net # Apenas para testes, depois remover
    restart: always

  rapitest:
    image: jarbounds/rapitest:latest
    depends_on:
      db:
        condition: service_started
      rabbitmq:
        condition: service_started
    ports:
        - "443:443"
    networks:
      - internal-net
      - external-net
    restart: always

  runtestsworkerservice:
    image: jarbounds/runtestsworkerservice:latest
    networks:
      - internal-net
    depends_on:
      db:
        condition: service_started
      rabbitmq:
        condition: service_started
    restart: always


  setuptestsworkerservice:
    image: jarbounds/setuptestsworkerservice:latest
    networks:
      - internal-net
    depends_on:
      db:
        condition: service_started
      rabbitmq:
        condition: service_started
    restart: always